# Generated by Django 4.2.5 on 2023-11-02 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_diets_countries_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='diets',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='diets',
            old_name='colories_pd_medium',
            new_name='colories',
        ),
        migrations.CreateModel(
            name='FavoritesDiets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ManyToManyField(to='main.diets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
