# Generated by Django 4.2.5 on 2023-11-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_type_category_rename_type_diets_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diets',
            name='category',
        ),
        migrations.RemoveField(
            model_name='diets',
            name='colories',
        ),
        migrations.AddField(
            model_name='diets',
            name='duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diets',
            name='fluid_intake_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diets',
            name='restrictions_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diets',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
